### ISSUE TITLE
U-Boot should support Edison out of the box

### ISSUE THREAD

**Issue by andy-shev** [01org/edison-u-boot#8]
The custom stuff in this repository has to be upstreamed at some point, otherwise the burden of supporting x86_64 kernel boot will be on users. This is not good.

**Comment by andy-shev** [comment]
Done.

**Comment by htot** [comment]
Thanks Andy, great work! BTW did you note the u-boot patch that will allow building without multilib? I think it will land in next release. This will enable building u-boot for x86-64 much more easily.

**Comment by andy-shev** [comment]
@htot 
Nope, I did not. Thanks for heads up. Will look at when have time.
