### ISSUE TITLE
edison-v2016.03 fails to build

### ISSUE THREAD

**Issue by cklin** [01org/edison-u-boot#9]
I am unable to build f581d4e93dfbd57b8b9b6b6b690021a852e2093b, which is the current head of branch edison-v2016.03.  The build commands I used:

```
make edison_defconfig
make all
```

Build error messages:

```
arch/x86/cpu/built-in.o: In function `config_pci_bridge':
/media/xvdi1/cklin/edison/kernel-build/edison-u-boot/arch/x86/cpu/tangier/pci.c:24: undefined reference to `pci_hose_scan_bus'
lib/built-in.o: In function `tick_to_time':
/media/xvdi1/cklin/edison/kernel-build/edison-u-boot/lib/time.c:103: undefined reference to `get_tbclk'
lib/built-in.o: In function `usec_to_tick':
/media/xvdi1/cklin/edison/kernel-build/edison-u-boot/lib/time.c:129: undefined reference to `get_tbclk'
Makefile:1171: recipe for target 'u-boot' failed
make: *** [u-boot] Error 1
```

**Comment by andy-shev** [comment]
`--- a/arch/x86/cpu/tangier/tangier.c
+++ b/arch/x86/cpu/tangier/tangier.c
@@ -183,8 +183,8 @@ int board_mmc_init(bd_t * bis)
 }
 
 /* ovveride get_tbclk_mhz code see tsc_timer */
-/* Get the speed of the TSC timer in MHz */
-unsigned __attribute__((no_instrument_function)) long get_tbclk_mhz(void)
+/* Get the speed of the TSC timer in Hz */
+unsigned __attribute__((no_instrument_function)) long get_tbclk(void)
 {
        u32 ratio , bus_freq;
        u64 platform_info = native_read_msr(MSR_PLATFORM_INFO);
@@ -225,8 +225,7 @@ unsigned __attribute__((no_instrument_function)) long get_tbclk_mhz(void)
                bus_freq = FSB_FREQ_100SKU;
                break;
        }
-       // return Freq in Mhz
-       return ((bus_freq * ratio)/1000);
+       return ((bus_freq * ratio) * 1000);
 }
 
 void reset_cpu(ulong addr)`

**Comment by andy-shev** [comment]
These changes shoud fix `get_tbclk()` issue:
-unsigned __attribute__((no_instrument_function)) long get_tbclk_mhz(void)
+unsigned __attribute__((no_instrument_function)) long get_tbclk(void)
-       return ((bus_freq * ratio)/1000);
+       return ((bus_freq * ratio) * 1000);

**Comment by andy-shev** [comment]
Okay, that's perhaps a wrong one, but no single branch is buildable to me.

**Comment by andy-shev** [comment]
@cklin Try my version here: https://github.com/andy-shev/u-boot/tree/edison

**Comment by andy-shev** [comment]
Simple use upstream U-Boot. Or if you want Yocto solution, consider unofficial community project: https://github.com/edison-fw.
